services:
  db:
    image: postgres:16
    container_name: rm562822_rm562145_db_clientes
    environment:
      POSTGRES_DB: cp2_cloud
      POSTGRES_USER: cp2_user
      POSTGRES_PASSWORD: cp2_password
    ports:
      - "5432:5432"
    volumes:
      - rm562822_rm562145_postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - rm562822_rm562145_network
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U cp2_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: ./app
    container_name: rm562822_rm562145_api_clientes
    environment:
      DB_HOST: db
      DB_NAME: cp2_cloud
      DB_USER: cp2_user
      DB_PASSWORD: cp2_password
      DB_PORT: 5432
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - rm562822_rm562145_network

volumes:
  rm562822_rm562145_postgres_data:

networks:
  rm562822_rm562145_network: